GroupProject/Controllers/CompanyProfilePageController.cs
using AutoMapper;
using GroupProject.DAL;
using GroupProject.Models.CompanyModels;
using GroupProject.Repositories;
using GroupProject.ViewModels;
using GroupProject.ViewModels.CompanyViewModels;
using Microsoft.AspNet.Identity;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace GroupProject.Controllers
{
    public class CompanyProfilePageController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly CompanyRepository companyRepository;
        private readonly JobsAppliedRepository jobsAppliedRepository;
        private readonly JobRepository jobRepository;
        private readonly UserRepository userRepository;
        private string userId => User.Identity.GetUserId();

        public CompanyProfilePageController()
        {
            db = new ApplicationDbContext();
            companyRepository = new CompanyRepository(db);
            jobsAppliedRepository = new JobsAppliedRepository(db);
            jobRepository = new JobRepository(db);
            userRepository = new UserRepository(db);
        }


        public ActionResult CompProfilePage()
        {
            var company = companyRepository.GetCompany(userId);
            if (company == null)
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);

            return View("../Company/ProfilePage/CompProfilePage", Mapper.Map<Company, CompanyFormViewModel>(company));
        }

        public ActionResult Home()
        {
            var user = db.Users.Include(u => u.Company).Include(u => u.Developer).SingleOrDefault(u => u.Id == userId);
            var photo = user.GetUserPhotoPath();

            var view = new UserViewModel()
            {
                UserId = userId,
                Name = user.IsDeveloper ? user.Developer.FullName : user.Company.CompanyName,
                UserImageUrl = user.GetUserPhotoPath(),
            };

            return PartialView("../User/HomePage", view);
        }

        public ActionResult About()
        {
            var company = companyRepository.GetCompany(userId);
            if (company == null)
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);

            return PartialView("../Company/ProfilePage/About", company);
        }

        [HttpGet]
        public ActionResult Jobs()
        {
            var jobs = jobRepository.GetCompJobs(userId);
            if (jobs == null)
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);

            var viewModel = new JobGetViewModel(jobs);

            return PartialView("../Company/ProfilePage/Jobs", viewModel);
        }

        [HttpGet]
        public ActionResult People()
        {
            var workers = userRepository.GetWorkers(userId);
            var workersViewModel = new List<CompanyPeopleViewModel>();

            foreach (var worker in workers)
            {
                workersViewModel.Add(new CompanyPeopleViewModel
                {
                    ImageName = worker.GetUserPhotoPath(),
                    FullName = worker.Developer.FullName,
                    JobTitle = worker.Developer.Experiences.FirstOrDefault().JobTitle,
                    DeveloperID=worker.Id
                });
            }

            return PartialView("../Company/ProfilePage/People", workersViewModel);
        }

        public ActionResult AddressForm()
        {
            return PartialView();
        }

        public ActionResult DetailsForm()
        {
            var company = companyRepository.VanillaCompany(userId);
            CompanyDetailsViewModel a = new CompanyDetailsViewModel
            {
                CompanyName = company.CompanyName,
                FoundationDate = company.FoundationDate,
                FounderName = company.FounderName,
                Description = company.Description
            };

            return PartialView(a);
        }

        public ActionResult Applicants()
        {
            var applicants = jobsAppliedRepository.GetApplicants(userId);
            if (applicants == null)
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);

            return PartialView("../Company/ProfilePage/Applicants", applicants);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
        }
    }
}

GroupProject/Controllers/DeveloperProfileController.cs
using AutoMapper;
using GroupProject.DAL;
using GroupProject.Models.DeveloperModels;
using GroupProject.Models.SharedModels;
using GroupProject.Repositories;
using GroupProject.ViewModels;
using GroupProject.ViewModels.DeveloperViewModels.ProfilePageViewModels;
using Microsoft.AspNet.Identity;
using System.Linq;
using System.Web.Mvc;

namespace GroupProject.Controllers
{
    public class DeveloperProfileController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly CompanyRepository _companyRepository;
        private readonly DeveloperRepository _developerRepository;
        private readonly AddressRepository _addressRepository;
        private string userId => User.Identity.GetUserId();

        public DeveloperProfileController()
        {
            _db = new ApplicationDbContext();
            _companyRepository = new CompanyRepository(_db);
            _developerRepository = new DeveloperRepository(_db);
            _addressRepository = new AddressRepository(_db);
        }
            
        public ActionResult DeveloperProfilePage()
        {
            var Id = User.Identity.GetUserId();
            var developer = _developerRepository.GetDeveloperForProfilePageWithID(Id);
            var devViewModel = Mapper.Map<Developer, DeveloperProfilePageViewModel>(developer);

            devViewModel.SortExperiencesWithNullsFirst();
            devViewModel.SortEducationsWithNullsFirst();

            return View(devViewModel);
        }

        public ActionResult AddressForm()  
        {
            var address = _addressRepository.GetAddressWithId(userId);

            AddressProfilePageViewModel a = Mapper.Map<Address, AddressProfilePageViewModel>(address);

            //Clears validation messages on first load
            ModelState.Clear();

            return PartialView(a);
        }

        public ActionResult DetailsForm(DeveloperDetailsViewModel det)
        {
            ModelState.Clear();
            return PartialView(det);
        }

        public ActionResult EducationForm(EducationProfilePageViewModel e)
        {
            ModelState.Clear();
            return PartialView(e);
        }

        public ActionResult ExperienceForm(ExperienceProfilePageViewModel ex)
        {
            ModelState.Clear();
            ex.CompaniesToChoose = _companyRepository.GetCompaniesNamesAndIDs();
           
            return PartialView(ex);
        }

        public ActionResult SkillForm()
        {
            var skills = _db.Skills.ToList();

            return PartialView(skills);
        }

        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
        }
    }
}

GroupProject/Controllers/JobController.cs
using GroupProject.DAL;
using GroupProject.Persistence;
using GroupProject.Repositories;
using GroupProject.ViewModels.CompanyViewModels;
using System.Net;
using System.Web.Mvc;

namespace GroupProject.Controllers
{
    [Authorize]
    public class JobController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly JobRepository jobRepository;
        private readonly UnitOfWork unitOfWork;

        public JobController()
        {
            db = new ApplicationDbContext();
            jobRepository = new JobRepository(db);
            unitOfWork = new UnitOfWork(db);
        }


        public ActionResult DevJobsPage()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateJob(JobPostViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            jobRepository.AddJobPosted(viewModel);

            unitOfWork.Save();
            return new HttpStatusCodeResult(HttpStatusCode.OK); //return Json();
        }

        [HttpDelete]
        public ActionResult DeleteJob(int id)
        {
            jobRepository.DeleteJob(id);

            unitOfWork.Save();
            return new HttpStatusCodeResult(HttpStatusCode.OK); //return Json();
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
        }
    }
}

GroupProject/Controllers/UserController.cs
using GroupProject.DAL;
using GroupProject.ViewModels;
using Microsoft.AspNet.Identity;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace GroupProject.Controllers
{
    public class UserController : Controller
    {
        private readonly ApplicationDbContext context;

        public UserController()
        {
            context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            context.Dispose();
        }


        public ActionResult Index()
        {
            return View();
        }

        public string UserPhotos(string Id)
        {
            //If no Id is given then get my photo
            var userId = Id ?? User.Identity.GetUserId();
            var user = context.Users.Include(u => u.Developer).FirstOrDefault(d => d.Id == userId);
            var photopath = user.GetUserPhotoPath();

            return user.GetUserPhotoPath();
        }

        public ActionResult NetworkPage()
        {
            return View();
        }

        public ActionResult HomePage()
        {
            var id = User.Identity.GetUserId();
            var user = context.Users.Include(u => u.Company).Include(u => u.Developer).SingleOrDefault(u => u.Id == id);
            var photo = user.GetUserPhotoPath();

            var view = new UserViewModel()
            {
                UserId = id,
                Name = user.IsDeveloper ? user.Developer.FullName : user.Company.CompanyName,
                UserImageUrl = user.GetUserPhotoPath(),
            };

            return View(view);
        }
    }
}

GroupProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>


    @Html.Partial("_NavBar")
    <br/>
    <br/>
    <br/>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>


    @if (User.Identity.IsAuthenticated)
    {

        <section class="chat-window-popup">
            <div class="chat-window-popup-title">
                <i>Click for Chatting</i>
            </div>

            <div class="chat-window-popup-title-btns">
                <span class="fa fa-angle-up"></span>
            </div>
        </section>

        <div class="chat-messaging-col">

            <div class="chat-current-chatting-user">
                <div class="chat-user-info">
                    <div class="chat-follower-photo" style="background: url('../../Images/UserProfilePics/NoImageMale.png');">
                        <span class="chat-is-user-active fa fa-circle"></span>
                    </div>
                </div>

                <div class="chat-follower-details">
                    <span class="chat-user-name"></span>

                </div>

            </div>

            <div id="show-messages" class="chat-message-window">

              
            </div>

            <div class="chat-message-input">
                <form id="msg-form">

                    <input type="text" name="msg" />

                    <button type="submit">Clickme</button>

                </form>
            </div>
        </div>

        <div class="chat-followers-col">

            <div class="chat-followers-search">
                <span class="fa fa-search"></span>
                <input type="text" name="searchFollowers" placeholder="Search Messages" />
            </div>

            <div class="chat-followers-list">

            </div>

        </div>

    }

    @Scripts.Render("~/bundles/lib")



    @if (User.Identity.IsAuthenticated)
    {
        <script src="~/Scripts/jquery.signalR-2.4.1.min.js"></script>
        <script src="~/signalr/hubs"></script>
        <script src="~/Scripts/Chat/HubBooter.js"></script>

        <script src="~/Scripts/Chat/popupClick.js"></script>



        <script src="~/Scripts/GD/notificationService.js"></script>
        <script src="~/Scripts/Chat/chatService.js"></script>



        @*<script src="~/Scripts/HomePageAC/VariousClasses/FeedHubSubscriber.js"></script>*@


    }
    @RenderSection("scripts", required: false)

</body>

</html>

GroupProject/Views/Shared/_NavBar.cshtml
@using GroupProject.Models

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">


            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>


            @*@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">

                @if (User.Identity.IsAuthenticated)
                {
                    <li>@Html.ActionLink("Network", "NetworkPage", "User")</li>
                    if (User.Identity.IsDeveloper())
                    {
                        <li>@Html.ActionLink("Home", "HomePage", "User")</li>
                        <li>@Html.ActionLink("Profile", "DeveloperProfilePage", "DeveloperProfile")</li>
                        <li>@Html.ActionLink("Jobs", "DevJobsPage", "Job")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Home", "HomePage", "User")</li>
                        <li>@Html.ActionLink("Profile", "CompProfilePage", "CompanyProfilePage")</li>
                    }
                }
            </ul>
                    @Html.Partial("_LoginPartial")
            </div>

        </div>
</div>