GroupProject/Controllers/OtherCompanyProfilePageController.cs
using AutoMapper;
using GroupProject.DAL;
using GroupProject.Models.CompanyModels;
using GroupProject.Repositories;
using GroupProject.ViewModels;
using GroupProject.ViewModels.CompanyViewModels;
using Microsoft.AspNet.Identity;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace GroupProject.Controllers
{
    [AllowAnonymous]
    public class OtherCompanyProfilePageController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly CompanyRepository companyRepository;
        private readonly JobRepository jobRepository;
        private readonly JobsAppliedRepository jobsAppliedRepository;
        private readonly UserRepository userRepository;

        public OtherCompanyProfilePageController()
        {
            db = new ApplicationDbContext();
            companyRepository = new CompanyRepository(db);
            jobRepository = new JobRepository(db);
            jobsAppliedRepository = new JobsAppliedRepository(db);
            userRepository = new UserRepository(db);
        }


        public ActionResult OtherCompProfilePage(string id)
        {
            //id = "0d753708-3172-4ea1-8aeb-9bea394f5f3a";
            var viewModel = Mapper.Map<Company, CompanyFormViewModel>(companyRepository.GetCompany(id));

            return View("../Company/OtherProfilePage/OtherCompProfilePage", viewModel);
        }

        public ActionResult Home(string companyId)
        {
            if (companyId == null)
                companyId = User.Identity.GetUserId();

            var user = db.Users.Include(u => u.Company).Include(u => u.Developer).SingleOrDefault(u => u.Id == companyId);
            var photo = user.GetUserPhotoPath();

            var view = new UserViewModel()
            {
                UserId = companyId,
                Name = user.IsDeveloper ? user.Developer.FullName : user.Company.CompanyName,
                UserImageUrl = user.GetUserPhotoPath(),
            };

            return PartialView("../User/OtherHomePage",view);
        }

        public ActionResult About(string companyId)
        {
            var company = companyRepository.GetCompany(companyId);
            if (company == null)
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);

            return PartialView("../Company/OtherProfilePage/_About", company);
        }

        public ActionResult Jobs(string companyId)
        {
            var jobs = jobRepository.GetCompJobs(companyId);
            if (jobs == null)
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);

            var viewModel = new JobGetViewModel(jobs);

            return PartialView("../Company/OtherProfilePage/_Jobs", viewModel);
        }

        [HttpGet]
        public ActionResult People(string companyId)
        {
            var workers = userRepository.GetWorkers(companyId);
            var workersViewModel = new List<CompanyPeopleViewModel>();

            foreach (var worker in workers)
            {
                workersViewModel.Add(new CompanyPeopleViewModel
                {
                    ImageName = worker.GetUserPhotoPath(),
                    FullName = worker.Developer.FullName,
                    JobTitle = worker.Developer.Experiences.FirstOrDefault().JobTitle,
                    DeveloperID=worker.Id
                });
            }

            return PartialView("../Company/OtherProfilePage/_People", workersViewModel);
        }

        public ActionResult Applicants(string companyId)
        {
            var applicants = jobsAppliedRepository.GetApplicants(companyId);
            if (applicants == null)
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);

            return PartialView("../Company/OtherProfilePage/_Applicants", applicants);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
        }
    }
}

GroupProject/Controllers/OtherDeveloperProfileController.cs
using AutoMapper;
using GroupProject.DAL;
using GroupProject.Models.DeveloperModels;
using GroupProject.Repositories;
using GroupProject.ViewModels.DeveloperViewModels.ProfilePageViewModels;
using System.Web.Mvc;

namespace GroupProject.Controllers
{
    [AllowAnonymous]
    public class OtherDeveloperProfileController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly CompanyRepository _companyRepository;
        private readonly DeveloperRepository _developerRepository;

        public OtherDeveloperProfileController()
        {
            _db = new ApplicationDbContext();
            _companyRepository = new CompanyRepository(_db);
            _developerRepository = new DeveloperRepository(_db);
        }

        public ActionResult OtherDeveloperProfilePage(string id)
        {
            var developer = _developerRepository.GetDeveloperForProfilePageWithID(id);
            var devViewModel = Mapper.Map<Developer, DeveloperProfilePageViewModel>(developer);

            devViewModel.SortExperiencesWithNullsFirst();
            devViewModel.SortEducationsWithNullsFirst();
            return View(devViewModel);
        }

        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
        }
    }
}

GroupProject/Controllers/UserController.cs
using GroupProject.DAL;
using GroupProject.ViewModels;
using Microsoft.AspNet.Identity;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace GroupProject.Controllers
{
    public class UserController : Controller
    {
        private readonly ApplicationDbContext context;

        public UserController()
        {
            context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            context.Dispose();
        }


        public ActionResult Index()
        {
            return View();
        }

        public string UserPhotos(string Id)
        {
            //If no Id is given then get my photo
            var userId = Id ?? User.Identity.GetUserId();
            var user = context.Users.Include(u => u.Developer).FirstOrDefault(d => d.Id == userId);
            var photopath = user.GetUserPhotoPath();

            return user.GetUserPhotoPath();
        }

        public ActionResult NetworkPage()
        {
            return View();
        }

        public ActionResult HomePage()
        {
            var id = User.Identity.GetUserId();
            var user = context.Users.Include(u => u.Company).Include(u => u.Developer).SingleOrDefault(u => u.Id == id);
            var photo = user.GetUserPhotoPath();

            var view = new UserViewModel()
            {
                UserId = id,
                Name = user.IsDeveloper ? user.Developer.FullName : user.Company.CompanyName,
                UserImageUrl = user.GetUserPhotoPath(),
            };

            return View(view);
        }
    }
}

GroupProject/Views/OtherDeveloperProfile/OtherDeveloperProfilePage.cshtml
@model GroupProject.ViewModels.DeveloperViewModels.ProfilePageViewModels.DeveloperProfilePageViewModel

@{
    ViewBag.Title = "DeveloperProfilePage";
}

<div class="container profile-page-container">
    <div class="panel-group">
        <div class="panel panel-default row">
            <div class="profile-images">
                <div class="background-profile-page-image">
                    <img id="background-pic" src="~/Images/UserProfilePics/bg-image.jpg" />
                </div>
                <div id="profilePic">
                    <label for="fileUpload">
                        <img id="profilePic2" />
                    </label>
                </div>
            </div>

            <div class="profileDetails">
                <div class="devDetails">
                    <span id="fullName"><strong>@Html.DisplayFor(m => m.FullName)</strong></span>
                    <div>
                        <span id="currentlyWorkingJobTitle">@Html.DisplayFor(m => m.CurrentJobTitle)</span>
                        <strong id="currentlyWorkingCompanyName">@Html.DisplayFor(m => m.WorksAt)</strong>
                    </div>
                    <div>
                        <span id="adrCity">@Html.DisplayFor(m => m.User.Address.City.CityName)</span>
                        <strong id="adrCountry">@Html.DisplayFor(m => m.User.Address.City.Country.CountryName)</strong>
                    </div>
                    <span><i>@Html.DisplayFor(m => m.User.UserName)</i></span>
                    <span><i>@Html.DisplayFor(m => m.Age)</i></span>
                    <span><i>@Html.DisplayFor(m => m.User.FollowersCount)</i></span>
                </div>
            </div>

        </div>

        <div class="panel-group">
            <div class="panel panel-default row devEdu">
                <div class="eduHeader  @(Model.Educations.Count != 0 ? "": "hidden")">
                    <div class="eduHeader2">
                        <h3><strong>Education</strong></h3>
                    </div>
                    <hr class="headerHr" />
                </div>
                <div class="devEduBody">
                    @if (Model.Educations.Count != 0)
                    {

                        for (int i = 0; i < Model.Educations.Count; i++)
                        {
                            <div class="Edu-@Model.Educations[i].EducationID">
                                <div class="devEducation">
                                    <div class="dev-parent" id='Edu-@Model.Educations[i].EducationID'>
                                        <div class="dev-child">
                                            @Html.LabelFor(m => m.Educations[i].School)
                                            @Html.DisplayFor(m => m.Educations[i].School)
                                            @Html.LabelFor(m => m.Educations[i].Degree)
                                            @Html.DisplayFor(m => m.Educations[i].Degree)
                                            <br />
                                            @Html.LabelFor(m => m.Educations[i].Field)
                                            @Html.DisplayFor(m => m.Educations[i].Field)
                                            @if (Model.Educations[i].Grade.HasValue)
                                            {
                                                @Html.LabelFor(m => m.Educations[i].Grade)
                                                @Html.DisplayFor(m => m.Educations[i].Grade)
                                            }
                                            <br />
                                            @Html.LabelFor(m => m.Educations[i].StartYear)
                                            @Html.DisplayFor(m => m.Educations[i].StartYear)
                                            <br />
                                            @Html.LabelFor(m => m.Educations[i].EndYear)
                                            @Html.DisplayFor(m => m.Educations[i].EndYear)
                                        </div>

                                    </div>
                                </div>
                                <hr class="rowHr" />
                            </div>
                        }
                    }
                </div>
            </div>
        </div>

        <div class="panel-group">
            <div class="panel panel-default row devExp">
                <div class="expHeader  @(Model.Experiences.Count != 0 ? "": "hidden")">
                    <div class="expHeader2">
                        <h3><strong>Experience</strong></h3>
                    </div>
                    <hr class="headerHr" />
                </div>
                <div class="devExpBody">
                    @if (Model.Experiences.Count != 0)
                    {

                        for (int i = 0; i < Model.Experiences.Count; i++)
                        {
                            <div class="Exp-@Model.Experiences[i].ExperienceID">
                                <div class="devExperience">
                                    <div class="dev-parent" id='Exp-@Model.Experiences[i].ExperienceID'>
                                        <div class="dev-child">
                                            @Html.LabelFor(m => m.Experiences[i].JobTitle)
                                            <span>@Html.DisplayFor(m => m.Experiences[i].JobTitle)</span>
                                            @Html.LabelFor(m => m.Experiences[i].CompanyName)
                                            @if (Model.Experiences[i].CompanyWorkingID != null)
                                            {
                                                @Html.ActionLink(Model.Experiences[i].CompanyName, "OtherCompProfilePage", "OtherCompanyProfilePage", new { id = Model.Experiences[i].CompanyWorkingID }, null)
                                            }
                                            else
                                            {
                                                <span>@Html.DisplayFor(m => m.Experiences[i].CompanyName)</span>
                                            }
                                            <br />
                                            @Html.LabelFor(m => m.Experiences[i].StartYear)
                                            <span>@Html.DisplayFor(m => m.Experiences[i].StartYear)</span>
                                            @Html.LabelFor(m => m.Experiences[i].EndYear)
                                            <span>@Html.DisplayFor(m => m.Experiences[i].EndYear)</span>
                                            <br />
                                            @Html.LabelFor(m => m.Experiences[i].ExperienceType)
                                            <span>@Html.DisplayFor(m => m.Experiences[i].ExperienceType)</span>
                                        </div>
                                    </div>
                                </div>
                                <hr class="rowHr" />
                            </div>
                        }
                    }
                </div>
            </div>

        </div>

        <div class="panel-group">
            <div class="panel panel-default row devSkills">
                <div class="skillHeader  @(Model.DeveloperSkills.Count != 0 ? "": "hidden")">
                    <div class="skillHeader2">
                        <h3><strong>Skills</strong></h3>
                    </div>
                    <hr class="headerHr" />
                </div>
                <div class="devSkillBody">
                    @if (Model.DeveloperSkills.Count != 0)
                    {

                        for (int i = 0; i < Model.DeveloperSkills.Count; i++)
                        {
                            <div class="Skill-@Model.DeveloperSkills[i].SkillID">
                                <div class="devSkill">
                                    <div class="dev-parent" id='Skill-@Model.DeveloperSkills[i].SkillID'>

                                        <div class="dev-child">  <span>@Html.DisplayFor(m => m.DeveloperSkills[i].Skill.SkillName)</span></div>

                                    </div>
                                </div>
                                <hr class="rowHr" />
                            </div>
                        }
                    }
                </div>
            </div>

        </div>

    </div>
</div>



@section scripts {
    <script src="~/Scripts/HomePageAC/Services/networkService.js"></script>
    <script src="~/Scripts/HomePageAC/Controllers/imageSelectionController.js"></script>
    <script>
        $(document).ready(function () {

            $("#profilePic2").attr("src", `@Html.Action("UserPhotos", "User")`);

            new ProfileImageSelectionController('#fileUpload', '#profilePic2');

            new ProfileImageSelectionController('#bg-fileUpload', '#background-pic');

        });  //DOCUMENT READY FINISH

    </script>

}